# Generated by Django 5.0.4 on 2024-07-21 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish_food', '0002_remove_fishfood_restock_date_remove_fishfood_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='fishfood',
            name='restock_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fishfood',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
