# Generated by Django 5.0.4 on 2024-07-21 14:33

import django.db.models.deletion
import utils.image_path
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish_food', '0003_fishfood_restock_date_fishfood_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fishfood',
            name='image',
        ),
        migrations.CreateModel(
            name='FishFoodImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=utils.image_path.fish_food_images, verbose_name='Картинка корма')),
                ('ffoodd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ffood_images', to='fish_food.fishfood', verbose_name='Корм для рыбы')),
            ],
            options={
                'verbose_name': 'Изображение корма рыб',
                'verbose_name_plural': 'Изображение корма рыбы',
            },
        ),
    ]
