# Generated by Django 5.0.4 on 2024-06-11 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fishcategory',
            old_name='title',
            new_name='name',
        ),
    ]
