# Generated by Django 5.0.4 on 2024-07-21 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish', '0002_remove_fish_restock_date_remove_fish_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='fish',
            name='restock_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fish',
            name='stock',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
