# Generated by Django 5.0.4 on 2024-07-21 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accessories', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessory',
            name='restock_date',
        ),
        migrations.RemoveField(
            model_name='accessory',
            name='stock',
        ),
    ]
