# Generated by Django 5.0.4 on 2024-07-21 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessories', '0002_remove_accessory_restock_date_remove_accessory_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accessoryimage',
            old_name='accessory',
            new_name='accessory_ac',
        ),
        migrations.AddField(
            model_name='accessory',
            name='restock_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accessory',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
